# Generated by Django 3.0.9 on 2021-10-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Assam', 'Assam'), ('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Comilla', 'Comilla'), ('Rangpur', 'Rangpur'), ('Thakurgaon', 'Thakurgaon')], max_length=50)),
            ],
        ),
    ]
